{"parents": [{"link": "../", "title": "API Reference"}], "prev": {"link": "../django-admin/", "title": "<code class=\"docutils literal notranslate\"><span class=\"pre\">django-admin</span></code> and <code class=\"docutils literal notranslate\"><span class=\"pre\">manage.py</span></code>"}, "next": {"link": "../files/", "title": "File handling"}, "title": "Django Exceptions", "meta": {}, "body": "<div class=\"section\" id=\"s-django-exceptions\">\n<span id=\"django-exceptions\"></span><h1>Django Exceptions<a class=\"headerlink\" href=\"#django-exceptions\" title=\"Permalink to this headline\">\u00b6</a></h1>\n<p>Django raises some of its own exceptions as well as standard Python exceptions.</p>\n<div class=\"section\" id=\"s-module-django.core.exceptions\">\n<span id=\"s-django-core-exceptions\"></span><span id=\"module-django.core.exceptions\"></span><span id=\"django-core-exceptions\"></span><h2>Django Core Exceptions<a class=\"headerlink\" href=\"#module-django.core.exceptions\" title=\"Permalink to this headline\">\u00b6</a></h2>\n<p>Django core exception classes are defined in <code class=\"docutils literal notranslate\"><span class=\"pre\">django.core.exceptions</span></code>.</p>\n<div class=\"section\" id=\"s-appregistrynotready\">\n<span id=\"appregistrynotready\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">AppRegistryNotReady</span></code><a class=\"headerlink\" href=\"#appregistrynotready\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.AppRegistryNotReady\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">AppRegistryNotReady</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#AppRegistryNotReady\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.AppRegistryNotReady\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>This exception is raised when attempting to use models before the <a class=\"reference internal\" href=\"../applications/#app-loading-process\"><span class=\"std std-ref\">app\nloading process</span></a>, which initializes the ORM, is\ncomplete.</p>\n</dd></dl>\n\n</div>\n<div class=\"section\" id=\"s-objectdoesnotexist\">\n<span id=\"objectdoesnotexist\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">ObjectDoesNotExist</span></code><a class=\"headerlink\" href=\"#objectdoesnotexist\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.ObjectDoesNotExist\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">ObjectDoesNotExist</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#ObjectDoesNotExist\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.ObjectDoesNotExist\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The base class for <a class=\"reference internal\" href=\"../models/class/#django.db.models.Model.DoesNotExist\" title=\"django.db.models.Model.DoesNotExist\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">Model.DoesNotExist</span></code></a> exceptions. A <code class=\"docutils literal notranslate\"><span class=\"pre\">try/except</span></code> for\n<code class=\"docutils literal notranslate\"><span class=\"pre\">ObjectDoesNotExist</span></code> will catch\n<a class=\"reference internal\" href=\"../models/class/#django.db.models.Model.DoesNotExist\" title=\"django.db.models.Model.DoesNotExist\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">DoesNotExist</span></code></a> exceptions for all models.</p>\n<p>See <a class=\"reference internal\" href=\"../models/querysets/#django.db.models.query.QuerySet.get\" title=\"django.db.models.query.QuerySet.get\"><code class=\"xref py py-meth docutils literal notranslate\"><span class=\"pre\">get()</span></code></a>.</p>\n</dd></dl>\n\n</div>\n<div class=\"section\" id=\"s-emptyresultset\">\n<span id=\"emptyresultset\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">EmptyResultSet</span></code><a class=\"headerlink\" href=\"#emptyresultset\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.EmptyResultSet\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">EmptyResultSet</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#EmptyResultSet\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.EmptyResultSet\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p><code class=\"docutils literal notranslate\"><span class=\"pre\">EmptyResultSet</span></code> may be raised during query generation if a query won\u2019t\nreturn any results. Most Django projects won\u2019t encounter this exception,\nbut it might be useful for implementing custom lookups and expressions.</p>\n</dd></dl>\n\n</div>\n<div class=\"section\" id=\"s-fullresultset\">\n<span id=\"fullresultset\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">FullResultSet</span></code><a class=\"headerlink\" href=\"#fullresultset\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.FullResultSet\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">FullResultSet</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#FullResultSet\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.FullResultSet\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd></dd></dl>\n\n<div class=\"versionadded\">\n<span class=\"title\">New in Django 4.2:</span> <p><code class=\"docutils literal notranslate\"><span class=\"pre\">FullResultSet</span></code> may be raised during query generation if a query will\nmatch everything. Most Django projects won\u2019t encounter this exception, but\nit might be useful for implementing custom lookups and expressions.</p>\n</div>\n</div>\n<div class=\"section\" id=\"s-fielddoesnotexist\">\n<span id=\"fielddoesnotexist\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">FieldDoesNotExist</span></code><a class=\"headerlink\" href=\"#fielddoesnotexist\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.FieldDoesNotExist\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">FieldDoesNotExist</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#FieldDoesNotExist\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.FieldDoesNotExist\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The <code class=\"docutils literal notranslate\"><span class=\"pre\">FieldDoesNotExist</span></code> exception is raised by a model\u2019s\n<code class=\"docutils literal notranslate\"><span class=\"pre\">_meta.get_field()</span></code> method when the requested field does not exist on the\nmodel or on the model\u2019s parents.</p>\n</dd></dl>\n\n</div>\n<div class=\"section\" id=\"s-multipleobjectsreturned\">\n<span id=\"multipleobjectsreturned\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">MultipleObjectsReturned</span></code><a class=\"headerlink\" href=\"#multipleobjectsreturned\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.MultipleObjectsReturned\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">MultipleObjectsReturned</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#MultipleObjectsReturned\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.MultipleObjectsReturned\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The base class for <a class=\"reference internal\" href=\"../models/class/#django.db.models.Model.MultipleObjectsReturned\" title=\"django.db.models.Model.MultipleObjectsReturned\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">Model.MultipleObjectsReturned</span></code></a> exceptions. A\n<code class=\"docutils literal notranslate\"><span class=\"pre\">try/except</span></code> for <code class=\"docutils literal notranslate\"><span class=\"pre\">MultipleObjectsReturned</span></code> will catch\n<a class=\"reference internal\" href=\"../models/class/#django.db.models.Model.MultipleObjectsReturned\" title=\"django.db.models.Model.MultipleObjectsReturned\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">MultipleObjectsReturned</span></code></a> exceptions for all\nmodels.</p>\n<p>See <a class=\"reference internal\" href=\"../models/querysets/#django.db.models.query.QuerySet.get\" title=\"django.db.models.query.QuerySet.get\"><code class=\"xref py py-meth docutils literal notranslate\"><span class=\"pre\">get()</span></code></a>.</p>\n</dd></dl>\n\n</div>\n<div class=\"section\" id=\"s-suspiciousoperation\">\n<span id=\"suspiciousoperation\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">SuspiciousOperation</span></code><a class=\"headerlink\" href=\"#suspiciousoperation\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.SuspiciousOperation\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">SuspiciousOperation</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#SuspiciousOperation\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.SuspiciousOperation\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The <a class=\"reference internal\" href=\"#django.core.exceptions.SuspiciousOperation\" title=\"django.core.exceptions.SuspiciousOperation\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">SuspiciousOperation</span></code></a> exception is raised when a user has\nperformed an operation that should be considered suspicious from a security\nperspective, such as tampering with a session cookie. Subclasses of\n<code class=\"docutils literal notranslate\"><span class=\"pre\">SuspiciousOperation</span></code> include:</p>\n<ul class=\"simple\">\n<li><code class=\"docutils literal notranslate\"><span class=\"pre\">DisallowedHost</span></code></li>\n<li><code class=\"docutils literal notranslate\"><span class=\"pre\">DisallowedModelAdminLookup</span></code></li>\n<li><code class=\"docutils literal notranslate\"><span class=\"pre\">DisallowedModelAdminToField</span></code></li>\n<li><code class=\"docutils literal notranslate\"><span class=\"pre\">DisallowedRedirect</span></code></li>\n<li><code class=\"docutils literal notranslate\"><span class=\"pre\">InvalidSessionKey</span></code></li>\n<li><code class=\"docutils literal notranslate\"><span class=\"pre\">RequestDataTooBig</span></code></li>\n<li><code class=\"docutils literal notranslate\"><span class=\"pre\">SuspiciousFileOperation</span></code></li>\n<li><code class=\"docutils literal notranslate\"><span class=\"pre\">SuspiciousMultipartForm</span></code></li>\n<li><code class=\"docutils literal notranslate\"><span class=\"pre\">SuspiciousSession</span></code></li>\n<li><code class=\"docutils literal notranslate\"><span class=\"pre\">TooManyFieldsSent</span></code></li>\n<li><code class=\"docutils literal notranslate\"><span class=\"pre\">TooManyFilesSent</span></code></li>\n</ul>\n<p>If a <code class=\"docutils literal notranslate\"><span class=\"pre\">SuspiciousOperation</span></code> exception reaches the ASGI/WSGI handler level\nit is logged at the <code class=\"docutils literal notranslate\"><span class=\"pre\">Error</span></code> level and results in\na <a class=\"reference internal\" href=\"../request-response/#django.http.HttpResponseBadRequest\" title=\"django.http.HttpResponseBadRequest\"><code class=\"xref py py-class docutils literal notranslate\"><span class=\"pre\">HttpResponseBadRequest</span></code></a>. See the <a class=\"reference internal\" href=\"../../topics/logging/\"><span class=\"doc\">logging\ndocumentation</span></a> for more information.</p>\n</dd></dl>\n\n<div class=\"versionchanged\">\n<span class=\"title\">Changed in Django 3.2.18:</span> <p><code class=\"docutils literal notranslate\"><span class=\"pre\">SuspiciousOperation</span></code> is raised when too many files are submitted.</p>\n</div>\n</div>\n<div class=\"section\" id=\"s-permissiondenied\">\n<span id=\"permissiondenied\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">PermissionDenied</span></code><a class=\"headerlink\" href=\"#permissiondenied\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.PermissionDenied\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">PermissionDenied</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#PermissionDenied\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.PermissionDenied\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The <a class=\"reference internal\" href=\"#django.core.exceptions.PermissionDenied\" title=\"django.core.exceptions.PermissionDenied\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">PermissionDenied</span></code></a> exception is raised when a user does not have\npermission to perform the action requested.</p>\n</dd></dl>\n\n</div>\n<div class=\"section\" id=\"s-viewdoesnotexist\">\n<span id=\"viewdoesnotexist\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">ViewDoesNotExist</span></code><a class=\"headerlink\" href=\"#viewdoesnotexist\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.ViewDoesNotExist\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">ViewDoesNotExist</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#ViewDoesNotExist\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.ViewDoesNotExist\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The <a class=\"reference internal\" href=\"#django.core.exceptions.ViewDoesNotExist\" title=\"django.core.exceptions.ViewDoesNotExist\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">ViewDoesNotExist</span></code></a> exception is raised by\n<a class=\"reference internal\" href=\"../urlresolvers/#module-django.urls\" title=\"django.urls\"><code class=\"xref py py-mod docutils literal notranslate\"><span class=\"pre\">django.urls</span></code></a> when a requested view does not exist.</p>\n</dd></dl>\n\n</div>\n<div class=\"section\" id=\"s-middlewarenotused\">\n<span id=\"middlewarenotused\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">MiddlewareNotUsed</span></code><a class=\"headerlink\" href=\"#middlewarenotused\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.MiddlewareNotUsed\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">MiddlewareNotUsed</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#MiddlewareNotUsed\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.MiddlewareNotUsed\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The <a class=\"reference internal\" href=\"#django.core.exceptions.MiddlewareNotUsed\" title=\"django.core.exceptions.MiddlewareNotUsed\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">MiddlewareNotUsed</span></code></a> exception is raised when a middleware is not\nused in the server configuration.</p>\n</dd></dl>\n\n</div>\n<div class=\"section\" id=\"s-improperlyconfigured\">\n<span id=\"improperlyconfigured\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">ImproperlyConfigured</span></code><a class=\"headerlink\" href=\"#improperlyconfigured\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.ImproperlyConfigured\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">ImproperlyConfigured</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#ImproperlyConfigured\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.ImproperlyConfigured\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The <a class=\"reference internal\" href=\"#django.core.exceptions.ImproperlyConfigured\" title=\"django.core.exceptions.ImproperlyConfigured\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">ImproperlyConfigured</span></code></a> exception is raised when Django is\nsomehow improperly configured \u2013 for example, if a value in <code class=\"docutils literal notranslate\"><span class=\"pre\">settings.py</span></code>\nis incorrect or unparseable.</p>\n</dd></dl>\n\n</div>\n<div class=\"section\" id=\"s-fielderror\">\n<span id=\"fielderror\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">FieldError</span></code><a class=\"headerlink\" href=\"#fielderror\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.FieldError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">FieldError</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#FieldError\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.FieldError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The <a class=\"reference internal\" href=\"#django.core.exceptions.FieldError\" title=\"django.core.exceptions.FieldError\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">FieldError</span></code></a> exception is raised when there is a problem with a\nmodel field. This can happen for several reasons:</p>\n<ul class=\"simple\">\n<li>A field in a model clashes with a field of the same name from an\nabstract base class</li>\n<li>An infinite loop is caused by ordering</li>\n<li>A keyword cannot be parsed from the filter parameters</li>\n<li>A field cannot be determined from a keyword in the query\nparameters</li>\n<li>A join is not permitted on the specified field</li>\n<li>A field name is invalid</li>\n<li>A query contains invalid order_by arguments</li>\n</ul>\n</dd></dl>\n\n</div>\n<div class=\"section\" id=\"s-validationerror\">\n<span id=\"validationerror\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">ValidationError</span></code><a class=\"headerlink\" href=\"#validationerror\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.ValidationError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">ValidationError</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#ValidationError\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.ValidationError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The <a class=\"reference internal\" href=\"#django.core.exceptions.ValidationError\" title=\"django.core.exceptions.ValidationError\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">ValidationError</span></code></a> exception is raised when data fails form or\nmodel field validation. For more information about validation, see\n<a class=\"reference internal\" href=\"../forms/validation/\"><span class=\"doc\">Form and Field Validation</span></a>,\n<a class=\"reference internal\" href=\"../models/instances/#validating-objects\"><span class=\"std std-ref\">Model Field Validation</span></a> and the\n<a class=\"reference internal\" href=\"../validators/\"><span class=\"doc\">Validator Reference</span></a>.</p>\n</dd></dl>\n\n<div class=\"section\" id=\"s-non-field-errors\">\n<span id=\"non-field-errors\"></span><h4><code class=\"docutils literal notranslate\"><span class=\"pre\">NON_FIELD_ERRORS</span></code><a class=\"headerlink\" href=\"#non-field-errors\" title=\"Permalink to this headline\">\u00b6</a></h4>\n<dl class=\"py data\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.NON_FIELD_ERRORS\">\n<code class=\"sig-name descname\"><span class=\"pre\">NON_FIELD_ERRORS</span></code><a class=\"headerlink\" href=\"#django.core.exceptions.NON_FIELD_ERRORS\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd></dd></dl>\n\n<p><code class=\"docutils literal notranslate\"><span class=\"pre\">ValidationError</span></code>s that don\u2019t belong to a particular field in a form\nor model are classified as <code class=\"docutils literal notranslate\"><span class=\"pre\">NON_FIELD_ERRORS</span></code>. This constant is used\nas a key in dictionaries that otherwise map fields to their respective\nlist of errors.</p>\n</div>\n</div>\n<div class=\"section\" id=\"s-badrequest\">\n<span id=\"badrequest\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">BadRequest</span></code><a class=\"headerlink\" href=\"#badrequest\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.BadRequest\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">BadRequest</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#BadRequest\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.BadRequest\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The <a class=\"reference internal\" href=\"#django.core.exceptions.BadRequest\" title=\"django.core.exceptions.BadRequest\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">BadRequest</span></code></a> exception is raised when the request cannot be\nprocessed due to a client error. If a <code class=\"docutils literal notranslate\"><span class=\"pre\">BadRequest</span></code> exception reaches the\nASGI/WSGI handler level it results in a\n<a class=\"reference internal\" href=\"../request-response/#django.http.HttpResponseBadRequest\" title=\"django.http.HttpResponseBadRequest\"><code class=\"xref py py-class docutils literal notranslate\"><span class=\"pre\">HttpResponseBadRequest</span></code></a>.</p>\n</dd></dl>\n\n</div>\n<div class=\"section\" id=\"s-requestaborted\">\n<span id=\"requestaborted\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">RequestAborted</span></code><a class=\"headerlink\" href=\"#requestaborted\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.RequestAborted\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">RequestAborted</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#RequestAborted\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.RequestAborted\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The <a class=\"reference internal\" href=\"#django.core.exceptions.RequestAborted\" title=\"django.core.exceptions.RequestAborted\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">RequestAborted</span></code></a> exception is raised when an HTTP body being read\nin by the handler is cut off midstream and the client connection closes,\nor when the client does not send data and hits a timeout where the server\ncloses the connection.</p>\n<p>It is internal to the HTTP handler modules and you are unlikely to see\nit elsewhere. If you are modifying HTTP handling code, you should raise\nthis when you encounter an aborted request to make sure the socket is\nclosed cleanly.</p>\n</dd></dl>\n\n</div>\n<div class=\"section\" id=\"s-synchronousonlyoperation\">\n<span id=\"synchronousonlyoperation\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">SynchronousOnlyOperation</span></code><a class=\"headerlink\" href=\"#synchronousonlyoperation\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.core.exceptions.SynchronousOnlyOperation\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">SynchronousOnlyOperation</span></code><a class=\"reference internal\" href=\"../../_modules/django/core/exceptions/#SynchronousOnlyOperation\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.core.exceptions.SynchronousOnlyOperation\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The <a class=\"reference internal\" href=\"#django.core.exceptions.SynchronousOnlyOperation\" title=\"django.core.exceptions.SynchronousOnlyOperation\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">SynchronousOnlyOperation</span></code></a> exception is raised when code that\nis only allowed in synchronous Python code is called from an asynchronous\ncontext (a thread with a running asynchronous event loop). These parts of\nDjango are generally heavily reliant on thread-safety to function and don\u2019t\nwork correctly under coroutines sharing the same thread.</p>\n<p>If you are trying to call code that is synchronous-only from an\nasynchronous thread, then create a synchronous thread and call it in that.\nYou can accomplish this is with <a class=\"reference internal\" href=\"../../topics/async/#asgiref.sync.sync_to_async\" title=\"asgiref.sync.sync_to_async\"><code class=\"xref py py-func docutils literal notranslate\"><span class=\"pre\">asgiref.sync.sync_to_async()</span></code></a>.</p>\n</dd></dl>\n\n</div>\n</div>\n<div class=\"section\" id=\"s-url-resolver-exceptions\">\n<span id=\"url-resolver-exceptions\"></span><h2>URL Resolver exceptions<a class=\"headerlink\" href=\"#url-resolver-exceptions\" title=\"Permalink to this headline\">\u00b6</a></h2>\n<p>URL Resolver exceptions are defined in <code class=\"docutils literal notranslate\"><span class=\"pre\">django.urls</span></code>.</p>\n<div class=\"section\" id=\"s-resolver404\">\n<span id=\"resolver404\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">Resolver404</span></code><a class=\"headerlink\" href=\"#resolver404\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.urls.Resolver404\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">Resolver404</span></code><a class=\"reference internal\" href=\"../../_modules/django/urls/exceptions/#Resolver404\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.urls.Resolver404\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The <a class=\"reference internal\" href=\"#django.urls.Resolver404\" title=\"django.urls.Resolver404\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">Resolver404</span></code></a> exception is raised by\n<a class=\"reference internal\" href=\"../urlresolvers/#django.urls.resolve\" title=\"django.urls.resolve\"><code class=\"xref py py-func docutils literal notranslate\"><span class=\"pre\">resolve()</span></code></a> if the path passed to <code class=\"docutils literal notranslate\"><span class=\"pre\">resolve()</span></code> doesn\u2019t\nmap to a view. It\u2019s a subclass of <a class=\"reference internal\" href=\"../../topics/http/views/#django.http.Http404\" title=\"django.http.Http404\"><code class=\"xref py py-class docutils literal notranslate\"><span class=\"pre\">django.http.Http404</span></code></a>.</p>\n</dd></dl>\n\n</div>\n<div class=\"section\" id=\"s-noreversematch\">\n<span id=\"noreversematch\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">NoReverseMatch</span></code><a class=\"headerlink\" href=\"#noreversematch\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.urls.NoReverseMatch\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">NoReverseMatch</span></code><a class=\"reference internal\" href=\"../../_modules/django/urls/exceptions/#NoReverseMatch\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.urls.NoReverseMatch\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p>The <a class=\"reference internal\" href=\"#django.urls.NoReverseMatch\" title=\"django.urls.NoReverseMatch\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">NoReverseMatch</span></code></a> exception is raised by <a class=\"reference internal\" href=\"../urlresolvers/#module-django.urls\" title=\"django.urls\"><code class=\"xref py py-mod docutils literal notranslate\"><span class=\"pre\">django.urls</span></code></a> when a\nmatching URL in your URLconf cannot be identified based on the parameters\nsupplied.</p>\n</dd></dl>\n\n</div>\n</div>\n<div class=\"section\" id=\"s-database-exceptions\">\n<span id=\"database-exceptions\"></span><h2>Database Exceptions<a class=\"headerlink\" href=\"#database-exceptions\" title=\"Permalink to this headline\">\u00b6</a></h2>\n<p>Database exceptions may be imported from <code class=\"docutils literal notranslate\"><span class=\"pre\">django.db</span></code>.</p>\n<p>Django wraps the standard database exceptions so that your Django code has a\nguaranteed common implementation of these classes.</p>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.db.Error\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">Error</span></code><a class=\"reference internal\" href=\"../../_modules/django/db/utils/#Error\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.db.Error\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd></dd></dl>\n\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.db.InterfaceError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">InterfaceError</span></code><a class=\"reference internal\" href=\"../../_modules/django/db/utils/#InterfaceError\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.db.InterfaceError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd></dd></dl>\n\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.db.DatabaseError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">DatabaseError</span></code><a class=\"reference internal\" href=\"../../_modules/django/db/utils/#DatabaseError\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.db.DatabaseError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd></dd></dl>\n\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.db.DataError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">DataError</span></code><a class=\"reference internal\" href=\"../../_modules/django/db/utils/#DataError\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.db.DataError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd></dd></dl>\n\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.db.OperationalError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">OperationalError</span></code><a class=\"reference internal\" href=\"../../_modules/django/db/utils/#OperationalError\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.db.OperationalError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd></dd></dl>\n\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.db.IntegrityError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">IntegrityError</span></code><a class=\"reference internal\" href=\"../../_modules/django/db/utils/#IntegrityError\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.db.IntegrityError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd></dd></dl>\n\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.db.InternalError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">InternalError</span></code><a class=\"reference internal\" href=\"../../_modules/django/db/utils/#InternalError\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.db.InternalError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd></dd></dl>\n\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.db.ProgrammingError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">ProgrammingError</span></code><a class=\"reference internal\" href=\"../../_modules/django/db/utils/#ProgrammingError\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.db.ProgrammingError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd></dd></dl>\n\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.db.NotSupportedError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">NotSupportedError</span></code><a class=\"reference internal\" href=\"../../_modules/django/db/utils/#NotSupportedError\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.db.NotSupportedError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd></dd></dl>\n\n<p>The Django wrappers for database exceptions behave exactly the same as\nthe underlying database exceptions. See <span class=\"target\" id=\"index-0\"></span><a class=\"pep reference external\" href=\"https://peps.python.org/pep-0249/\"><strong>PEP 249</strong></a>, the Python Database API\nSpecification v2.0, for further information.</p>\n<p>As per <span class=\"target\" id=\"index-1\"></span><a class=\"pep reference external\" href=\"https://peps.python.org/pep-3134/\"><strong>PEP 3134</strong></a>, a <code class=\"docutils literal notranslate\"><span class=\"pre\">__cause__</span></code> attribute is set with the original\n(underlying) database exception, allowing access to any additional\ninformation provided.</p>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.db.models.ProtectedError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-prename descclassname\"><span class=\"pre\">models.</span></code><code class=\"sig-name descname\"><span class=\"pre\">ProtectedError</span></code><a class=\"headerlink\" href=\"#django.db.models.ProtectedError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd></dd></dl>\n\n<p>Raised to prevent deletion of referenced objects when using\n<a class=\"reference internal\" href=\"../models/fields/#django.db.models.PROTECT\" title=\"django.db.models.PROTECT\"><code class=\"xref py py-attr docutils literal notranslate\"><span class=\"pre\">django.db.models.PROTECT</span></code></a>. <a class=\"reference internal\" href=\"#django.db.models.ProtectedError\" title=\"django.db.models.ProtectedError\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">models.ProtectedError</span></code></a> is a subclass\nof <a class=\"reference internal\" href=\"#django.db.IntegrityError\" title=\"django.db.IntegrityError\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">IntegrityError</span></code></a>.</p>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.db.models.RestrictedError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-prename descclassname\"><span class=\"pre\">models.</span></code><code class=\"sig-name descname\"><span class=\"pre\">RestrictedError</span></code><a class=\"headerlink\" href=\"#django.db.models.RestrictedError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd></dd></dl>\n\n<p>Raised to prevent deletion of referenced objects when using\n<a class=\"reference internal\" href=\"../models/fields/#django.db.models.RESTRICT\" title=\"django.db.models.RESTRICT\"><code class=\"xref py py-attr docutils literal notranslate\"><span class=\"pre\">django.db.models.RESTRICT</span></code></a>. <a class=\"reference internal\" href=\"#django.db.models.RestrictedError\" title=\"django.db.models.RestrictedError\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">models.RestrictedError</span></code></a> is a subclass\nof <a class=\"reference internal\" href=\"#django.db.IntegrityError\" title=\"django.db.IntegrityError\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">IntegrityError</span></code></a>.</p>\n</div>\n<div class=\"section\" id=\"s-http-exceptions\">\n<span id=\"http-exceptions\"></span><h2>HTTP Exceptions<a class=\"headerlink\" href=\"#http-exceptions\" title=\"Permalink to this headline\">\u00b6</a></h2>\n<p>HTTP exceptions may be imported from <code class=\"docutils literal notranslate\"><span class=\"pre\">django.http</span></code>.</p>\n<div class=\"section\" id=\"s-unreadableposterror\">\n<span id=\"unreadableposterror\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">UnreadablePostError</span></code><a class=\"headerlink\" href=\"#unreadableposterror\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.http.UnreadablePostError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">UnreadablePostError</span></code><a class=\"reference internal\" href=\"../../_modules/django/http/request/#UnreadablePostError\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.http.UnreadablePostError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p><a class=\"reference internal\" href=\"#django.http.UnreadablePostError\" title=\"django.http.UnreadablePostError\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">UnreadablePostError</span></code></a> is raised when a user cancels an upload.</p>\n</dd></dl>\n\n</div>\n</div>\n<div class=\"section\" id=\"s-sessions-exceptions\">\n<span id=\"sessions-exceptions\"></span><h2>Sessions Exceptions<a class=\"headerlink\" href=\"#sessions-exceptions\" title=\"Permalink to this headline\">\u00b6</a></h2>\n<p>Sessions exceptions are defined in <code class=\"docutils literal notranslate\"><span class=\"pre\">django.contrib.sessions.exceptions</span></code>.</p>\n<div class=\"section\" id=\"s-sessioninterrupted\">\n<span id=\"sessioninterrupted\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">SessionInterrupted</span></code><a class=\"headerlink\" href=\"#sessioninterrupted\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.contrib.sessions.exceptions.SessionInterrupted\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">SessionInterrupted</span></code><a class=\"reference internal\" href=\"../../_modules/django/contrib/sessions/exceptions/#SessionInterrupted\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.contrib.sessions.exceptions.SessionInterrupted\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p><a class=\"reference internal\" href=\"#django.contrib.sessions.exceptions.SessionInterrupted\" title=\"django.contrib.sessions.exceptions.SessionInterrupted\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">SessionInterrupted</span></code></a> is raised when a session is destroyed in a\nconcurrent request. It\u2019s a subclass of\n<a class=\"reference internal\" href=\"#django.core.exceptions.BadRequest\" title=\"django.core.exceptions.BadRequest\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">BadRequest</span></code></a>.</p>\n</dd></dl>\n\n</div>\n</div>\n<div class=\"section\" id=\"s-transaction-exceptions\">\n<span id=\"transaction-exceptions\"></span><h2>Transaction Exceptions<a class=\"headerlink\" href=\"#transaction-exceptions\" title=\"Permalink to this headline\">\u00b6</a></h2>\n<p>Transaction exceptions are defined in <code class=\"docutils literal notranslate\"><span class=\"pre\">django.db.transaction</span></code>.</p>\n<div class=\"section\" id=\"s-transactionmanagementerror\">\n<span id=\"transactionmanagementerror\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">TransactionManagementError</span></code><a class=\"headerlink\" href=\"#transactionmanagementerror\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.db.transaction.TransactionManagementError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-name descname\"><span class=\"pre\">TransactionManagementError</span></code><a class=\"reference internal\" href=\"../../_modules/django/db/transaction/#TransactionManagementError\"><span class=\"viewcode-link\"><span class=\"pre\">[source]</span></span></a><a class=\"headerlink\" href=\"#django.db.transaction.TransactionManagementError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p><a class=\"reference internal\" href=\"#django.db.transaction.TransactionManagementError\" title=\"django.db.transaction.TransactionManagementError\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">TransactionManagementError</span></code></a> is raised for any and all problems\nrelated to database transactions.</p>\n</dd></dl>\n\n</div>\n</div>\n<div class=\"section\" id=\"s-testing-framework-exceptions\">\n<span id=\"testing-framework-exceptions\"></span><h2>Testing Framework Exceptions<a class=\"headerlink\" href=\"#testing-framework-exceptions\" title=\"Permalink to this headline\">\u00b6</a></h2>\n<p>Exceptions provided by the <code class=\"docutils literal notranslate\"><span class=\"pre\">django.test</span></code> package.</p>\n<div class=\"section\" id=\"s-redirectcycleerror\">\n<span id=\"redirectcycleerror\"></span><h3><code class=\"docutils literal notranslate\"><span class=\"pre\">RedirectCycleError</span></code><a class=\"headerlink\" href=\"#redirectcycleerror\" title=\"Permalink to this headline\">\u00b6</a></h3>\n<dl class=\"py exception\">\n<dt class=\"sig sig-object py\" id=\"django.test.client.RedirectCycleError\">\n<em class=\"property\"><span class=\"pre\">exception</span><span class=\"w\"> </span></em><code class=\"sig-prename descclassname\"><span class=\"pre\">client.</span></code><code class=\"sig-name descname\"><span class=\"pre\">RedirectCycleError</span></code><a class=\"headerlink\" href=\"#django.test.client.RedirectCycleError\" title=\"Permalink to this definition\">\u00b6</a></dt>\n<dd><p><a class=\"reference internal\" href=\"#django.test.client.RedirectCycleError\" title=\"django.test.client.RedirectCycleError\"><code class=\"xref py py-exc docutils literal notranslate\"><span class=\"pre\">RedirectCycleError</span></code></a> is raised when the test client detects a\nloop or an overly long chain of redirects.</p>\n</dd></dl>\n\n</div>\n</div>\n<div class=\"section\" id=\"s-python-exceptions\">\n<span id=\"python-exceptions\"></span><h2>Python Exceptions<a class=\"headerlink\" href=\"#python-exceptions\" title=\"Permalink to this headline\">\u00b6</a></h2>\n<p>Django raises built-in Python exceptions when appropriate as well. See the\nPython documentation for further information on the <a class=\"reference external\" href=\"https://docs.python.org/3/library/exceptions.html#bltin-exceptions\" title=\"(in Python v3.11)\"><span>Built-in Exceptions</span></a>.</p>\n</div>\n</div>\n", "metatags": "", "rellinks": [["genindex", "General Index", "I", "index"], ["py-modindex", "Python Module Index", "", "modules"], ["ref/files/index", "File handling", "N", "next"], ["ref/django-admin", "<code class=\"docutils literal notranslate\"><span class=\"pre\">django-admin</span></code> and <code class=\"docutils literal notranslate\"><span class=\"pre\">manage.py</span></code>", "P", "previous"]], "sourcename": "ref/exceptions.txt", "toc": "<ul>\n<li><a class=\"reference internal\" href=\"#\">Django Exceptions</a><ul>\n<li><a class=\"reference internal\" href=\"#module-django.core.exceptions\">Django Core Exceptions</a><ul>\n<li><a class=\"reference internal\" href=\"#appregistrynotready\"><code class=\"docutils literal notranslate\"><span class=\"pre\">AppRegistryNotReady</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#objectdoesnotexist\"><code class=\"docutils literal notranslate\"><span class=\"pre\">ObjectDoesNotExist</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#emptyresultset\"><code class=\"docutils literal notranslate\"><span class=\"pre\">EmptyResultSet</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#fullresultset\"><code class=\"docutils literal notranslate\"><span class=\"pre\">FullResultSet</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#fielddoesnotexist\"><code class=\"docutils literal notranslate\"><span class=\"pre\">FieldDoesNotExist</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#multipleobjectsreturned\"><code class=\"docutils literal notranslate\"><span class=\"pre\">MultipleObjectsReturned</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#suspiciousoperation\"><code class=\"docutils literal notranslate\"><span class=\"pre\">SuspiciousOperation</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#permissiondenied\"><code class=\"docutils literal notranslate\"><span class=\"pre\">PermissionDenied</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#viewdoesnotexist\"><code class=\"docutils literal notranslate\"><span class=\"pre\">ViewDoesNotExist</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#middlewarenotused\"><code class=\"docutils literal notranslate\"><span class=\"pre\">MiddlewareNotUsed</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#improperlyconfigured\"><code class=\"docutils literal notranslate\"><span class=\"pre\">ImproperlyConfigured</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#fielderror\"><code class=\"docutils literal notranslate\"><span class=\"pre\">FieldError</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#validationerror\"><code class=\"docutils literal notranslate\"><span class=\"pre\">ValidationError</span></code></a><ul>\n<li><a class=\"reference internal\" href=\"#non-field-errors\"><code class=\"docutils literal notranslate\"><span class=\"pre\">NON_FIELD_ERRORS</span></code></a></li>\n</ul>\n</li>\n<li><a class=\"reference internal\" href=\"#badrequest\"><code class=\"docutils literal notranslate\"><span class=\"pre\">BadRequest</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#requestaborted\"><code class=\"docutils literal notranslate\"><span class=\"pre\">RequestAborted</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#synchronousonlyoperation\"><code class=\"docutils literal notranslate\"><span class=\"pre\">SynchronousOnlyOperation</span></code></a></li>\n</ul>\n</li>\n<li><a class=\"reference internal\" href=\"#url-resolver-exceptions\">URL Resolver exceptions</a><ul>\n<li><a class=\"reference internal\" href=\"#resolver404\"><code class=\"docutils literal notranslate\"><span class=\"pre\">Resolver404</span></code></a></li>\n<li><a class=\"reference internal\" href=\"#noreversematch\"><code class=\"docutils literal notranslate\"><span class=\"pre\">NoReverseMatch</span></code></a></li>\n</ul>\n</li>\n<li><a class=\"reference internal\" href=\"#database-exceptions\">Database Exceptions</a></li>\n<li><a class=\"reference internal\" href=\"#http-exceptions\">HTTP Exceptions</a><ul>\n<li><a class=\"reference internal\" href=\"#unreadableposterror\"><code class=\"docutils literal notranslate\"><span class=\"pre\">UnreadablePostError</span></code></a></li>\n</ul>\n</li>\n<li><a class=\"reference internal\" href=\"#sessions-exceptions\">Sessions Exceptions</a><ul>\n<li><a class=\"reference internal\" href=\"#sessioninterrupted\"><code class=\"docutils literal notranslate\"><span class=\"pre\">SessionInterrupted</span></code></a></li>\n</ul>\n</li>\n<li><a class=\"reference internal\" href=\"#transaction-exceptions\">Transaction Exceptions</a><ul>\n<li><a class=\"reference internal\" href=\"#transactionmanagementerror\"><code class=\"docutils literal notranslate\"><span class=\"pre\">TransactionManagementError</span></code></a></li>\n</ul>\n</li>\n<li><a class=\"reference internal\" href=\"#testing-framework-exceptions\">Testing Framework Exceptions</a><ul>\n<li><a class=\"reference internal\" href=\"#redirectcycleerror\"><code class=\"docutils literal notranslate\"><span class=\"pre\">RedirectCycleError</span></code></a></li>\n</ul>\n</li>\n<li><a class=\"reference internal\" href=\"#python-exceptions\">Python Exceptions</a></li>\n</ul>\n</li>\n</ul>\n", "display_toc": true, "page_source_suffix": ".txt", "current_page_name": "ref/exceptions", "sidebars": ["localtoc.html", "relations.html", "sourcelink.html", "searchbox.html"], "customsidebar": null, "favicon_url": null, "logo_url": null, "alabaster_version": "0.7.13", "include_console_assets": false}
