{"parents": [{"link": "../", "title": "Release notes"}], "prev": {"link": "../1.4.11/", "title": "Django 1.4.11 release notes"}, "next": {"link": "../1.4.9/", "title": "Django 1.4.9 release notes"}, "title": "Django 1.4.10 release notes", "meta": {}, "body": "<div class=\"section\" id=\"s-django-1-4-10-release-notes\">\n<span id=\"django-1-4-10-release-notes\"></span><h1>Django 1.4.10 release notes<a class=\"headerlink\" href=\"#django-1-4-10-release-notes\" title=\"Permalink to this headline\">\u00b6</a></h1>\n<p><em>November 6, 2013</em></p>\n<p>Django 1.4.10 fixes a Python-compatibility bug in the 1.4 series.</p>\n<div class=\"section\" id=\"s-python-compatibility\">\n<span id=\"python-compatibility\"></span><h2>Python compatibility<a class=\"headerlink\" href=\"#python-compatibility\" title=\"Permalink to this headline\">\u00b6</a></h2>\n<p>Django 1.4.9 inadvertently introduced issues with Python 2.5 compatibility.\nDjango 1.4.10 restores Python 2.5 compatibility. This was issue #21362 in\nDjango\u2019s Trac.</p>\n</div>\n</div>\n", "metatags": "", "rellinks": [["genindex", "General Index", "I", "index"], ["py-modindex", "Python Module Index", "", "modules"], ["releases/1.4.9", "Django 1.4.9 release notes", "N", "next"], ["releases/1.4.11", "Django 1.4.11 release notes", "P", "previous"]], "sourcename": "releases/1.4.10.txt", "toc": "<ul>\n<li><a class=\"reference internal\" href=\"#\">Django 1.4.10 release notes</a><ul>\n<li><a class=\"reference internal\" href=\"#python-compatibility\">Python compatibility</a></li>\n</ul>\n</li>\n</ul>\n", "display_toc": true, "page_source_suffix": ".txt", "current_page_name": "releases/1.4.10", "sidebars": ["localtoc.html", "relations.html", "sourcelink.html", "searchbox.html"], "customsidebar": null, "favicon_url": null, "logo_url": null, "alabaster_version": "0.7.13", "include_console_assets": false}